title: SUNYCell Project
description: Documentation for the SUNYCell Project and ecosystem.
theme: just-the-docs

url: https://sunycell.github.io

aux_links:
  Template Repository: https://github.com/sunycell/sunycell.github.io

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red